# Generated by Django 5.2.1 on 2025-05-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_ordencompra_codigo_ordencompra_condiciones_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='codigo',
            field=models.CharField(default='ORD-001', max_length=50),
        ),
    ]
