# Generated by Django 5.2.1 on 2025-05-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_detalleordencompra_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
