# Generated by Django 5.2 on 2025-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_historialaprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=150),
            preserve_default=False,
        ),
    ]
