# Generated by Django 5.2 on 2025-05-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0003_requerimiento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
