# Generated by Django 5.2.1 on 2025-05-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0004_requerimiento_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('sin_ejecutar', 'Sin Ejecutar'), ('emitida', 'Emitida'), ('recibida', 'Recibida'), ('completa', 'Completa'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
    ]
