# Generated by Django 5.2 on 2025-05-22 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0005_alter_requerimiento_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialaprobacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de Aprobación', 'verbose_name_plural': 'Historial de Aprobaciones'},
        ),
        migrations.AlterField(
            model_name='historialaprobacion',
            name='accion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialaprobacion',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimientos.requerimiento'),
        ),
        migrations.AlterField(
            model_name='historialaprobacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
