# Generated by Django 5.2 on 2025-05-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0006_alter_historialaprobacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerequerimiento',
            options={'verbose_name': 'Detalle de Requerimiento', 'verbose_name_plural': 'Detalles de Requerimientos'},
        ),
        migrations.AlterModelOptions(
            name='requerimiento',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Requerimiento', 'verbose_name_plural': 'Requerimientos'},
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='aprobador',
            field=models.ForeignKey(blank=True, help_text='Usuario que aprobó o rechazó el requerimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del requerimiento', null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la aprobación/rechazo', null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='observacion',
            field=models.TextField(blank=True, help_text='Comentario del aprobador sobre la decisión', null=True),
        ),
        migrations.AlterField(
            model_name='historialaprobacion',
            name='accion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('creado', 'Creado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialaprobacion',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_aprobaciones', to='requerimientos.requerimiento'),
        ),
        migrations.AlterField(
            model_name='historialaprobacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso')], default='pendiente', max_length=20),
        ),
    ]
