# Generated by Django 5.2 on 2025-05-20 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_activo_departamento_codigo_and_more'),
        ('usuarios', '0002_remove_usuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamentos.departamento'),
        ),
    ]
